# Generated by Django 5.2.6 on 2025-10-16 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('category', models.CharField(choices=[('competition', '竞赛'), ('thesis', '论文'), ('patent', '专利'), ('scholarship', '奖学金'), ('other', '其他')], max_length=20, verbose_name='类别')),
                ('level', models.CharField(max_length=50, verbose_name='级别')),
                ('score', models.FloatField(verbose_name='对应分值')),
                ('description', models.TextField(blank=True, verbose_name='项目说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('student_id', models.CharField(default='000000', max_length=20, verbose_name='学号')),
                ('major', models.CharField(default='未填写', max_length=50, verbose_name='专业')),
                ('grade', models.CharField(default='2023级', max_length=20, verbose_name='年级')),
                ('total_score', models.FloatField(default=0, verbose_name='总加分')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(default='', upload_to='proofs/', verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('score_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.scoreitem', verbose_name='申请加分项目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentprofile', verbose_name='提交学生')),
            ],
        ),
    ]
