# Generated by Django 5.2.6 on 2025-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default='000000', max_length=20, unique=True, verbose_name='学号'),
        ),
    ]
