# Generated by Django 5.2.7 on 2025-10-16 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scoreitem', verbose_name='申请加分项目'),
        ),
    ]
