# Generated by Django 5.2.6 on 2025-10-17 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_submission_score_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='入学时间'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(default='未填写', max_length=20, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='submission',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='补充说明'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核驳回'), ('revoked', '已撤回')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
