# Generated by Django 5.2.6 on 2025-10-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_submission_options_alter_submission_proof_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='admission_date',
        ),
    ]
