# Generated by Django 5.2.6 on 2025-10-25 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_teacherprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreitem',
            options={'verbose_name': '加分项目', 'verbose_name_plural': '加分项目'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': '学生档案', 'verbose_name_plural': '学生档案'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': '提交记录', 'verbose_name_plural': '提交记录'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.scoreitem', verbose_name='加分项目'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核拒绝'), ('revoked', '已撤回')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentprofile', verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='StudentInfoChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='修改字段')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='修改前值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='修改后值')),
                ('change_time', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info_edits', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_logs', to='students.studentprofile')),
            ],
            options={
                'verbose_name': '学生信息变更日志',
                'verbose_name_plural': '学生信息变更日志',
                'ordering': ['-change_time'],
            },
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
