# Generated by Django 5.2.6 on 2025-10-18 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('teacher_id', models.CharField(default='000000', max_length=20, unique=True, verbose_name='工号')),
                ('department', models.CharField(default='未填写', max_length=50, verbose_name='部门')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
