# Generated by Django 4.2.10 on 2025-12-03 14:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', '学生'), ('TEACHER', '老师'), ('ADMIN', '管理员')], default='STUDENT', max_length=10, verbose_name='用户角色')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号')),
                ('teacher_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='教职工号')),
                ('rank_visible', models.BooleanField(default=False, verbose_name='排名显示开关')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='条款类别')),
                ('content', models.TextField(verbose_name='条款内容')),
                ('score_range', models.CharField(max_length=50, verbose_name='加分范围')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
            ],
            options={
                'verbose_name': '加分条款',
                'verbose_name_plural': '加分条款',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ScoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_score', models.FloatField(verbose_name='自评分数')),
                ('score_item', models.CharField(max_length=200, verbose_name='加分项目')),
                ('proof_file', models.FileField(upload_to='proofs/%Y/%m/%d/', verbose_name='加分证明文件')),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=10, verbose_name='审批状态')),
                ('approved_score', models.FloatField(blank=True, null=True, verbose_name='审批通过分数')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='驳回理由')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '加分申请',
                'verbose_name_plural': '加分申请',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('volunteer', '志愿服务'), ('cadre', '学生干部'), ('honor', '荣誉称号')], max_length=20, verbose_name='加分类型')),
                ('volunteer_hours', models.FloatField(blank=True, default=0, null=True, verbose_name='志愿服务时长（小时）')),
                ('is_large_event', models.BooleanField(default=False, verbose_name='是否大型赛会/支教（工时减半）')),
                ('cadre_role', models.CharField(blank=True, choices=[('monitor', '班长/团支书'), ('minister', '院学生会部长'), ('member', '班委/委员')], max_length=20, null=True, verbose_name='职务')),
                ('cadre_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='辅导员打分（0-100）')),
                ('honor_level', models.CharField(blank=True, choices=[('national', '国家级'), ('provincial', '省级'), ('school', '校级')], max_length=20, null=True, verbose_name='荣誉级别')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to=settings.AUTH_USER_MODEL, verbose_name='关联学生')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('competition', '学业竞赛'), ('paper', '学术论文'), ('patent', '国家专利'), ('innovation', '创新创业项目')], max_length=20, verbose_name='加分类型')),
                ('competition_level', models.CharField(blank=True, choices=[('national_a_plus', '国家级A+类'), ('national_a', '国家级A类'), ('national_a_minus', '国家级A-类'), ('provincial_a', '省级A类')], max_length=20, null=True, verbose_name='竞赛级别')),
                ('competition_rank', models.CharField(blank=True, choices=[('first', '一等奖及以上'), ('second', '二等奖'), ('third', '三等奖')], max_length=10, null=True, verbose_name='获奖等级')),
                ('is_group', models.BooleanField(default=False, verbose_name='是否团体项目')),
                ('group_role', models.CharField(blank=True, choices=[('independent', '独立作者'), ('first', '第一作者/队长'), ('second', '第二作者/队员')], max_length=15, null=True, verbose_name='团体角色')),
                ('paper_level', models.CharField(blank=True, choices=[('a', 'A类期刊/会议'), ('b', 'B类期刊/会议'), ('c', 'C类期刊/会议')], max_length=10, null=True, verbose_name='论文级别')),
                ('paper_author', models.CharField(blank=True, choices=[('independent', '独立作者'), ('first', '第一作者/队长'), ('second', '第二作者/队员')], max_length=15, null=True, verbose_name='作者排名')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_scores', to=settings.AUTH_USER_MODEL, verbose_name='关联学生')),
            ],
        ),
    ]
