# Generated by Django 4.2 on 2025-12-06 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicscore',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_score', to='score_helper.scoreapplication', verbose_name='关联申请'),
        ),
        migrations.AddField(
            model_name='performancescore',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_score', to='score_helper.scoreapplication', verbose_name='关联申请'),
        ),
        migrations.AddField(
            model_name='scoreapplication',
            name='apply_type',
            field=models.CharField(choices=[('academic', '学业加分'), ('performance', '表现加分')], default='academic', max_length=20, verbose_name='申请类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoreapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='scoreapplication',
            name='proof_file',
            field=models.FileField(upload_to='proofs/%Y/%m/%d/', verbose_name='证明文件（图片/文档）'),
        ),
        migrations.AlterField(
            model_name='scoreapplication',
            name='score_item',
            field=models.CharField(max_length=200, verbose_name='加分项目详情'),
        ),
    ]
